-- Converted from MySQL to PostgreSQL (Supabase)
-- Generated at 2026-03-18T13:10:34.663Z
-- Review the result before production usage.

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "username" VARCHAR(100) NOT NULL,
  "email" VARCHAR(191) NOT NULL,
  "password_hash" VARCHAR(255) NOT NULL,
  "terms_version_accepted" VARCHAR(32) NULL,
  "terms_accepted_at" TIMESTAMPTZ NULL,
  "privacy_version_accepted" VARCHAR(32) NULL,
  "privacy_accepted_at" TIMESTAMPTZ NULL,
  "marketing_consent" BOOLEAN NOT NULL DEFAULT FALSE,
  "marketing_consent_updated_at" TIMESTAMPTZ NULL,
  "data_retention_until" TIMESTAMPTZ NULL,
  "last_login_at" TIMESTAMPTZ NULL,
  "is_guest" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT "users_username_unique" UNIQUE (username),
  CONSTRAINT "users_email_unique" UNIQUE (email)
);
CREATE INDEX IF NOT EXISTS "users_data_retention_idx" ON "users" (data_retention_until);
CREATE INDEX IF NOT EXISTS "users_is_guest_idx" ON "users" (is_guest);

CREATE TABLE IF NOT EXISTS "user_region_inventory" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" INT NOT NULL,
  "region_id" INT NOT NULL,
  "nova_crystal" INT NOT NULL DEFAULT 0,
  "nova_shards" INT NOT NULL DEFAULT 0,
  "star_crystal" INT NOT NULL DEFAULT 0,
  "gemstone" INT NOT NULL DEFAULT 0,
  "wild_shards" INT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT "user_region_inventory_unique" UNIQUE (user_id, region_id),
  CONSTRAINT user_region_inventory_user_fk FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "user_region_inventory_user_idx" ON "user_region_inventory" (user_id);
CREATE INDEX IF NOT EXISTS "user_region_inventory_region_idx" ON "user_region_inventory" (region_id);

CREATE TABLE IF NOT EXISTS "user_app_state" (
  "user_id" INT NOT NULL,
  "app_state_json" JSONB NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id),
  CONSTRAINT user_app_state_user_fk FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "user_audit_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" INT NULL,
  "event_type" VARCHAR(80) NOT NULL,
  "event_payload" JSONB NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT user_audit_log_user_fk FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "user_audit_log_user_idx" ON "user_audit_log" (user_id);
CREATE INDEX IF NOT EXISTS "user_audit_log_event_idx" ON "user_audit_log" (event_type);

-- Keep "updated_at" in sync (replacement for MySQL ON UPDATE CURRENT_TIMESTAMP)
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "trg_set_updated_at_users" ON "users";
CREATE TRIGGER "trg_set_updated_at_users"
BEFORE UPDATE ON "users"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS "trg_set_updated_at_user_region_inventory" ON "user_region_inventory";
CREATE TRIGGER "trg_set_updated_at_user_region_inventory"
BEFORE UPDATE ON "user_region_inventory"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS "trg_set_updated_at_user_app_state" ON "user_app_state";
CREATE TRIGGER "trg_set_updated_at_user_app_state"
BEFORE UPDATE ON "user_app_state"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();
